-- ⚠️ 자동 생성 파일 — 직접 수정하지 말 것.
-- 원본: frontend/customer/src/mock/restaurant-menu.js
-- 생성기: dev/gen_dev_menu_sql.mjs
-- 용도: 개발 서버 시작 시 STORE001 의 메뉴/카테고리만 mock 데이터로 초기화.
--
-- 주의: order_items 의 menu_id FK 때문에, 실행측(dev_reset)에서
--       PRAGMA foreign_keys=OFF 로 감싸 실행한다.

-- STORE001 이 없으면 아무 것도 하지 않도록, 실행측에서 존재 보장(seed) 후 호출한다.

-- 1) 기존 메뉴/카테고리 제거 (해당 매장 한정)
DELETE FROM menus      WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001');
DELETE FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001');

-- 2) 카테고리 삽입
INSERT INTO categories(store_id, name, display_order, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), '브런치', 0, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO categories(store_id, name, display_order, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), '애피타이저', 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO categories(store_id, name, display_order, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), '샐러드', 2, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO categories(store_id, name, display_order, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), '수프', 3, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO categories(store_id, name, display_order, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), '파스타', 4, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO categories(store_id, name, display_order, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), '피자', 5, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO categories(store_id, name, display_order, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), '메인 · 그릴', 6, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO categories(store_id, name, display_order, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), '버거 · 샌드위치', 7, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO categories(store_id, name, display_order, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), '사이드', 8, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO categories(store_id, name, display_order, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), '디저트', 9, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO categories(store_id, name, display_order, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), '커피 · 티', 10, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO categories(store_id, name, display_order, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), '음료', 11, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO categories(store_id, name, display_order, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), '와인 · 칵테일', 12, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));

-- 3) 메뉴 삽입 (category_id 는 방금 삽입한 카테고리를 name 으로 참조)
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '브런치'), '에그 베네딕트', 16500, '잉글리시 머핀 위에 수란과 훈제 햄, 진한 홀란데이즈 소스', 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=900&q=70', 0, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '브런치'), '아보카도 토스트', 14000, '사워도우 위에 으깬 아보카도, 방울토마토, 포치드 에그', 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=70', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '브런치'), '벨기에 와플', 13500, '바삭한 리에주 와플에 메이플 시럽과 계절 베리', 'https://images.unsplash.com/photo-1533920379810-6bedac9e31df?auto=format&fit=crop&w=900&q=70', 2, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '브런치'), '버터밀크 팬케이크', 13000, '폭신한 3단 팬케이크, 휘핑버터와 메이플 시럽', 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=900&q=70', 3, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '브런치'), '프렌치 토스트', 14500, '브리오슈를 바닐라 커스터드에 적셔 구운 클래식', 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=900&q=70', 4, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '브런치'), '클래식 브렉퍼스트', 18000, '스크램블 에그, 소시지, 베이컨, 구운 토마토, 토스트', 'https://images.unsplash.com/photo-1494597564530-871f2b93ac55?auto=format&fit=crop&w=900&q=70', 5, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '브런치'), '샥슈카', 15000, '토마토 스튜에 반숙 계란, 페타치즈, 구운 바게트', 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=900&q=70', 6, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '브런치'), '그래놀라 요거트볼', 11500, '그릭요거트에 홈메이드 그래놀라와 제철 과일', 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=70', 7, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '애피타이저'), '브루스케타', 11000, '구운 바게트에 토마토·바질·엑스트라버진 올리브오일', 'https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&w=900&q=70', 0, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '애피타이저'), '갈릭 감바스', 16500, '통새우를 마늘과 올리브오일에 지글지글 익힌 스페인식', 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=70', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '애피타이저'), '모짜렐라 스틱', 10500, '겉바속촉 치즈스틱, 마리나라 디핑소스', 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?auto=format&fit=crop&w=900&q=70', 2, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '애피타이저'), '나초 그란데', 13000, '토르티야칩에 체다·할라피뇨·과카몰리·사워크림', 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?auto=format&fit=crop&w=900&q=70', 3, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '애피타이저'), '치킨 윙 (6pcs)', 14000, '스모키 바비큐 또는 스파이시 버팔로 소스', 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?auto=format&fit=crop&w=900&q=70', 4, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '애피타이저'), '부라타 카프레제', 17000, '크리미한 부라타와 방울토마토, 바질 페스토', 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=900&q=70', 5, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '애피타이저'), '트러플 감자튀김', 12000, '트러플오일과 파르미지아노를 뿌린 프렌치프라이', 'https://images.unsplash.com/photo-1432139509613-5c4255815697?auto=format&fit=crop&w=900&q=70', 6, 0, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '애피타이저'), '오늘의 수제 딥 플래터', 15500, '후무스·바바가누쉬·차치키와 따뜻한 피타', 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=900&q=70', 7, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '샐러드'), '시저 샐러드', 13000, '로메인, 크루통, 파르미지아노, 앤초비 시저드레싱', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=70', 0, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '샐러드'), '부라타 가든 샐러드', 16000, '어린잎, 부라타, 방울토마토, 발사믹 글레이즈', 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=70', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '샐러드'), '그릭 샐러드', 13500, '오이·토마토·올리브·페타치즈에 오레가노 드레싱', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=70', 2, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '샐러드'), '퀴노아 파워볼', 15000, '퀴노아·아보카도·병아리콩·구운 채소', 'https://images.unsplash.com/photo-1523986371872-9d3ba2e2f642?auto=format&fit=crop&w=900&q=70', 3, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '샐러드'), '연어 포케볼', 17500, '생연어·에다마메·오이·아보카도·간장 드레싱', 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=900&q=70', 4, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '샐러드'), '카프레제 샐러드', 14000, '모짜렐라·토마토·바질에 올리브오일', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=70', 5, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '샐러드'), '콥 샐러드', 15500, '치킨·베이컨·계란·아보카도·블루치즈', 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=70', 6, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '수프'), '토마토 바질 수프', 9500, '완숙 토마토를 오래 끓여낸 크리미 수프, 바질오일', 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?auto=format&fit=crop&w=900&q=70', 0, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '수프'), '버섯 크림 수프', 10500, '양송이·표고를 넣은 진한 크림 수프', 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=70', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '수프'), '프렌치 어니언 수프', 11500, '캐러멜라이즈드 양파와 그뤼에르 치즈 토스트', 'https://images.unsplash.com/photo-1543826173-70651703c5a4?auto=format&fit=crop&w=900&q=70', 2, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '수프'), '클램 차우더', 12500, '조개와 감자가 들어간 뉴잉글랜드식 크림 수프', 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=900&q=70', 3, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '수프'), '펌킨 수프', 10000, '단호박을 곱게 갈아 만든 부드러운 가을 수프', 'https://images.unsplash.com/photo-1590301157890-4810ed352733?auto=format&fit=crop&w=900&q=70', 4, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '수프'), '똠얌꿍', 13000, '새우와 레몬그라스 향의 매콤새콤한 타이 수프', 'https://images.unsplash.com/photo-1608219992759-8d74ed8d76eb?auto=format&fit=crop&w=900&q=70', 5, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '파스타'), '까르보나라', 16000, '판체타·계란노른자·페코리노로 만든 정통 로마식', 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=900&q=70', 0, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '파스타'), '알리오 올리오', 13500, '마늘과 페페론치노, 올리브오일의 담백한 파스타', 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=900&q=70', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '파스타'), '볼로네제', 16500, '소고기 라구를 오래 끓인 진한 미트소스 파스타', 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=70', 2, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '파스타'), '감바스 알리오', 18000, '통새우와 마늘, 화이트와인의 오일 파스타', 'https://images.unsplash.com/photo-1559737558-2f5a35f4523b?auto=format&fit=crop&w=900&q=70', 3, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '파스타'), '트러플 크림 파스타', 19000, '트러플향 크림소스에 버섯을 더한 페투치네', 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=900&q=70', 4, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '파스타'), '해산물 토마토 파스타', 18500, '홍합·오징어·새우가 가득한 토마토 링귀네', 'https://images.unsplash.com/photo-1559737558-2f5a35f4523b?auto=format&fit=crop&w=900&q=70', 5, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '파스타'), '페스토 뇨끼', 16000, '바질페스토에 버무린 감자 뇨끼와 잣', 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=900&q=70', 6, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '파스타'), '라자냐', 17500, '겹겹이 쌓은 미트소스와 베샤멜, 모짜렐라', 'https://images.unsplash.com/photo-1595295333158-4742f28fbd85?auto=format&fit=crop&w=900&q=70', 7, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '피자'), '마르게리타', 15000, '토마토·모짜렐라·바질의 나폴리 클래식', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=900&q=70', 0, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '피자'), '페퍼로니', 16500, '매콤한 페퍼로니가 가득한 아메리칸 스타일', 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=70', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '피자'), '콰트로 포르마지', 18000, '고르곤졸라·모짜렐라·파르미지아노·부라타', 'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=900&q=70', 2, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '피자'), '프로슈토 루꼴라', 19000, '생햄과 루꼴라, 파르미지아노 플레이크', 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=70', 3, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '피자'), '트러플 머쉬룸', 19500, '트러플오일과 버섯, 모짜렐라의 화이트 피자', 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=900&q=70', 4, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '피자'), '디아볼라', 17500, '매운 살라미와 할라피뇨의 스파이시 피자', 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=70', 5, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '피자'), '고르곤졸라 (꿀 포함)', 17000, '고르곤졸라 피자와 아카시아 꿀 디핑', 'https://images.unsplash.com/photo-1571066811602-716837d681de?auto=format&fit=crop&w=900&q=70', 6, 0, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '메인 · 그릴'), '채끝 스테이크 200g', 39000, '숙성 채끝등심을 미디엄으로 구워 로즈마리 버터와', 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=900&q=70', 0, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '메인 · 그릴'), '안심 스테이크 180g', 46000, '부드러운 안심에 레드와인 데미글라스', 'https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=900&q=70', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '메인 · 그릴'), '바비큐 폭립', 32000, '6시간 저온 조리한 스모키 바비큐 등갈비', 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=70', 2, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '메인 · 그릴'), '그릴드 램찹', 42000, '허브 마리네이드한 양갈비 구이', 'https://images.unsplash.com/photo-1607330289024-1535c6b4e1c1?auto=format&fit=crop&w=900&q=70', 3, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '메인 · 그릴'), '로스트 치킨 (하프)', 26000, '레몬과 타임으로 구운 촉촉한 반마리 치킨', 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?auto=format&fit=crop&w=900&q=70', 4, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '메인 · 그릴'), '팬시어드 연어', 29000, '겉은 바삭 속은 촉촉한 연어에 레몬버터소스', 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=900&q=70', 5, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '메인 · 그릴'), '비프 웰링턴', 52000, '페이스트리로 감싸 구운 안심의 정수', 'https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=900&q=70', 6, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '버거 · 샌드위치'), '클래식 치즈버거', 15500, '수제 패티·체다·양상추·토마토·특제소스', 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=900&q=70', 0, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '버거 · 샌드위치'), '베이컨 더블버거', 18500, '더블 패티와 바삭 베이컨, 캐러멜 어니언', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=70', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '버거 · 샌드위치'), '머쉬룸 스위스버거', 17000, '소테한 버섯과 스위스치즈의 풍미', 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=70', 2, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '버거 · 샌드위치'), '크리스피 치킨버거', 15000, '통닭다리살 튀김에 슬로와 스파이시 마요', 'https://images.unsplash.com/photo-1553909489-cd47e0ef937f?auto=format&fit=crop&w=900&q=70', 3, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '버거 · 샌드위치'), '클럽 샌드위치', 14500, '치킨·베이컨·계란·토마토의 3단 샌드위치', 'https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=900&q=70', 4, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '버거 · 샌드위치'), '풀드포크 샌드위치', 15500, '바비큐 풀드포크와 코울슬로', 'https://images.unsplash.com/photo-1553909489-cd47e0ef937f?auto=format&fit=crop&w=900&q=70', 5, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '버거 · 샌드위치'), '베지 랩', 12500, '구운 채소와 후무스를 넣은 통밀 랩', 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=70', 6, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '사이드'), '프렌치 프라이', 7000, '바삭하게 튀긴 감자튀김, 케첩·마요', 'https://images.unsplash.com/photo-1607013251379-e6eecfffe234?auto=format&fit=crop&w=900&q=70', 0, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '사이드'), '트러플 프라이', 9500, '트러플오일과 파마산을 뿌린 감자튀김', 'https://images.unsplash.com/photo-1607013251379-e6eecfffe234?auto=format&fit=crop&w=900&q=70', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '사이드'), '어니언 링', 8000, '두툼한 양파링 튀김', 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=900&q=70', 2, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '사이드'), '갈릭 브레드', 7500, '마늘버터를 발라 구운 바게트', 'https://images.unsplash.com/photo-1544982503-9f984c14501a?auto=format&fit=crop&w=900&q=70', 3, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '사이드'), '프라이드 치킨 (4pcs)', 12000, '겉바속촉 순살 프라이드치킨', 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=900&q=70', 4, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '사이드'), '구운 채소 모둠', 9000, '제철 채소를 올리브오일에 그릴', 'https://images.unsplash.com/photo-1518013431117-eb1465fa5752?auto=format&fit=crop&w=900&q=70', 5, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '사이드'), '매쉬드 포테이토', 7000, '부드러운 버터 감자 퓌레', 'https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=900&q=70', 6, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '디저트'), '뉴욕 치즈케이크', 9500, '진하고 크리미한 클래식 치즈케이크', 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=900&q=70', 0, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '디저트'), '티라미수', 9000, '마스카포네와 에스프레소의 이탈리안 디저트', 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=900&q=70', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '디저트'), '초콜릿 라바 케이크', 10000, '따뜻하게 흘러내리는 초콜릿과 바닐라 아이스크림', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=70', 2, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '디저트'), '제철 과일 타르트', 9500, '커스터드와 신선한 계절 과일', 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=900&q=70', 3, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '디저트'), '수제 젤라또 (3스쿱)', 8500, '바닐라·피스타치오·딸기 중 선택', 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?auto=format&fit=crop&w=900&q=70', 4, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '디저트'), '크렘 브륄레', 9000, '바삭한 캐러멜 층 아래 부드러운 바닐라 크림', 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=900&q=70', 5, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '디저트'), '브라우니 선데', 9500, '따뜻한 브라우니에 아이스크림과 초코소스', 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=900&q=70', 6, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '커피 · 티'), '아메리카노', 5000, '깊고 진한 에스프레소에 물을 더한 클래식', 'https://images.unsplash.com/photo-1461023058943-07f4c68edaf9?auto=format&fit=crop&w=900&q=70', 0, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '커피 · 티'), '카페 라떼', 5500, '부드러운 스팀밀크와 에스프레소', 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=70', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '커피 · 티'), '카푸치노', 5500, '벨벳 같은 우유거품의 카푸치노', 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=900&q=70', 2, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '커피 · 티'), '플랫 화이트', 6000, '진한 리스트레토에 마이크로폼', 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=70', 3, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '커피 · 티'), '바닐라 라떼', 6000, '바닐라 시럽을 더한 달콤한 라떼', 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=70', 4, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '커피 · 티'), '아이스 콜드브루', 6000, '12시간 저온 추출한 부드러운 콜드브루', 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=900&q=70', 5, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '커피 · 티'), '녹차 라떼', 6000, '고소한 우유와 진한 말차', 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?auto=format&fit=crop&w=900&q=70', 6, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '커피 · 티'), '캐모마일 티', 5500, '은은한 향의 허브 티', 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?auto=format&fit=crop&w=900&q=70', 7, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '음료'), '생과일 오렌지주스', 6500, '갓 짜낸 100% 오렌지주스', 'https://images.unsplash.com/photo-1437418747212-8d9709afab22?auto=format&fit=crop&w=900&q=70', 0, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '음료'), '수제 레모네이드', 6000, '상큼한 레몬과 탄산의 조화', 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=70', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '음료'), '딸기 스무디', 7000, '생딸기와 요거트를 갈아 만든 스무디', 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=70', 2, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '음료'), '망고 스무디', 7000, '달콤한 망고 스무디', 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=70', 3, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '음료'), '콜라 / 사이다', 3500, '탄산음료', 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=900&q=70', 4, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '음료'), '탄산수 (페리에)', 4500, '깔끔한 스파클링 워터', 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=900&q=70', 5, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '음료'), '생강 레몬 하이볼(무알콜)', 6500, '진저에일과 레몬의 무알콜 목테일', 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=70', 6, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '와인 · 칵테일'), '하우스 레드 와인 (글라스)', 9000, '미디엄 바디의 데일리 레드', 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=900&q=70', 0, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '와인 · 칵테일'), '하우스 화이트 와인 (글라스)', 9000, '산뜻한 드라이 화이트', 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=900&q=70', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '와인 · 칵테일'), '스파클링 (글라스)', 11000, '축하에 어울리는 브뤼 스파클링', 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=900&q=70', 2, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '와인 · 칵테일'), '아페롤 스프리츠', 12000, '아페롤·프로세코·소다의 상큼한 이탈리안 칵테일', 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=900&q=70', 3, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '와인 · 칵테일'), '모히토', 12000, '라임과 민트, 럼의 클래식 칵테일', 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=900&q=70', 4, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '와인 · 칵테일'), '진토닉', 12000, '보태니컬 진과 토닉워터', 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=900&q=70', 5, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '와인 · 칵테일'), '생맥주 (500ml)', 8000, '시원한 드래프트 라거', 'https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&w=900&q=70', 6, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));
INSERT INTO menus(store_id, category_id, name, price, description, image_url, display_order, is_available, created_at, updated_at) VALUES ((SELECT id FROM stores WHERE store_code = 'STORE001'), (SELECT id FROM categories WHERE store_id = (SELECT id FROM stores WHERE store_code = 'STORE001') AND name = '와인 · 칵테일'), '올드 패션드', 14000, '버번과 비터스의 정통 위스키 칵테일', 'https://images.unsplash.com/photo-1470158499416-75be9aa0c4db?auto=format&fit=crop&w=900&q=70', 7, 1, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));

-- 완료: 카테고리 13개, 메뉴 95개
